version: '3.8'

services:
  deno:
    image: denoland/deno
    container_name: deno
    restart: always
    volumes:
      - ./x5rating-frontend:/app
    working_dir: /app
    command: deno task start --allow-net
    networks:
      - x5-net
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    networks:
      - x5-net
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email vlad@kelonmyosa.ru -d x5rating.ru --agree-t>
    networks:
      - x5-net

networks:
  x5-net:
    driver: bridge